---
- name: Create Redmine backup data
  hosts: all
  become: true

  roles:
    - role: mamono210.redmine_backup_files
      tags:
        - backup_files

    - role: mamono210.redmine_backup_git
      tags:
        - backup_git

    - role: mamono210.redmine_backup_postgresql
      tags:
        - backup_postgresql

    - role: mamono210.redmine_facts
      tags:
        - facts
