---
version: 2.1

executors:
  trailing-whitespace:
    docker:
      - image: ghcr.io/docker-images-mamono210/circleci-executors/trailing-whitespace:latest
    resource_class: small

orbs:
  ansible-lint: orbss/ansible-lint@0.0.3
  aws-cli: circleci/aws-cli@3.1.1
  molecule-ec2: orbss/molecule-ec2@0.0.4
  yamllint: orbss/yamllint@0.0.4

jobs:
  ansible-lint:
    executor: ansible-lint/default
    steps:
      - checkout
      - ansible-lint/execute:
          molecule-playbook-test: true
  molecule-ec2:
    executor: molecule-ec2/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
          role-arn: ${AWS_ROLE_ARN}
          role-session-name: molecule_redmine_create-backup
          session-duration: '3600'
      - run:
          name: Set required environment variables
          command: |
            echo "export AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}-molecule" >> $BASH_ENV
            echo "export AWS_S3_OBJECT_NAME=redmica/centos-stream8/${AWS_S3_OBJECT_NAME}" >> $BASH_ENV
            echo "export LOCAL_FILE_NAME=${AWS_S3_OBJECT_NAME}" >> $BASH_ENV
            source $BASH_ENV
      - molecule-ec2/execute:
          aws-ami-name: "redmica_restore_centos-stream8*"
          aws-ami-owner-id: "808683561341"
          aws-resource-name: "molecule_redmine_create-backup"
          aws-vpc-subnet-id: "subnet-022a704b3061b8b39"
          circleci-timeout: "15m"
        environment:
        # AWS_S3_BUCKET_NAME: stored in system environment variables
        # AWS_S3_OBJECT_NAME: stored in system environment variables
        # LOCAL_FILE_NAME: stored in system environment variables
  yamllint:
    executor: yamllint/default
    steps:
      - checkout
      - yamllint/execute
  trailing-whitespace:
    executor: trailing-whitespace
    steps:
      - checkout
      - run:
          name: Execute trailing-whitespace
          command: trailing-whitespace

workflows:
  version: 2.1
  build:
    jobs:
      - trailing-whitespace
      - yamllint:
          requires:
            - trailing-whitespace
      - ansible-lint:
          requires:
            - yamllint
      - molecule-ec2:
          context: AWS_OPENID_CONNECT_TOKENS
          requires:
            - ansible-lint
