---
- name: Delete working directory
  ansible.builtin.file:
    path: '{{ redmine_backup_data_dir }}'
    state: absent

- name: Create working directory
  ansible.builtin.file:
    path: '{{ redmine_backup_data_dir }}'
    recurse: yes
    state: directory

- name: Archive Git repositories
  community.general.files.archive:
    path: "{{ redmine_git_dir }}"
    dest: "{{ redmine_backup_data_dir }}/{{ redmine_archived_git_file }}"
    mode: 0755

- name: Archive Redmine media files
  community.general.files.archive:
    path: "{{ redmine_dir }}/files"
    dest: "{{ redmine_backup_data_dir }}/{{ redmine_archived_media_file }}"
    mode: 0755

- name: Dump Redmine database
  ansible.builtin.shell:
    "pg_dump -h localhost -U {{ redmine_db_user }} {{ redmine_db_name }} > {{ redmine_backup_data_dir }}/{{ redmine_pg_dump_file }}"
  changed_when: False
  environment:
    PGPASSWORD: '{{ redmine_db_password }}'

- name: Archive all data
  community.general.files.archive:
    path: '{{ redmine_backup_data_dir }}'
    dest: "{{ redmine_backup_data_dir }}/{{ redmine_backup_archive_file }}"
    mode: 0755
