---
name: build
on: [deployment, push]

jobs:
  ansible-lint:
    uses: github-actions-reusable-workflows/ansible-lint/.github/workflows/workflows.yml@main

  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Yelp detect-secrets
        run: |
          pip install detect-secrets

      - name: Execulte detect-secrets(disabled KeywordDetector plugin)
        run: |
          detect-secrets scan --disable-plugin KeywordDetector \
          | jq .results > results.json

      - name: Check whether detect-secrets found vulnerability
        run: |
          line=$(cat results.json | wc -w)
          if [ $line -gt 2 ]; then
            echo "vulnerability was found"
            detect-secrets scan | jq .results -C
            exit 1;
          fi

      - name: Show detect-secrets version
        run: |
          pip list | grep detect-secrets \
          | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
          | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
          | GREP_COLORS='mt=01;33' egrep --color=always 'detect-secrets.* '

  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: centos-stream8
            platform: redmica
            python_interpreter: /usr/libexec/platform-python

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set Ansible Python interpreter
        run: |
          INTERPRETER=`which python`
          echo "ANSIBLE_PYTHON_INTERPRETER=${INTERPRETER}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install -r molecule/requirements.txt

      - name: Install required Ansible Collections and roles
        run: |
          ansible-galaxy collection install community.molecule
          ansible-galaxy install -r molecule/default/requirements.yml

      - name: Create galaxy dependencies file in 'molecule/default/'
        run: |
          cp roles/requirements.yml molecule/default/requirements.yml

      - name: Set environment variable with timestamp for making sure Molecule would create unique AWS resources
        run: |
          TIMESTAMP=$(date --date "9 hours" "+%Y%m%d_%H%M%S")
          echo "AWSIAM_USER=molecule_redmine_create-backup_${TIMESTAMP}_${{ matrix.distro }}" >> $GITHUB_ENV
          echo "AWSIAM_POLICY_NAME=molecule_redmine_create-backup_${TIMESTAMP}_${{ matrix.distro }}" >> $GITHUB_ENV

      - name: Create AWS Access Key
        run: |
          molecule dependency --scenario-name awsiam
          molecule converge --scenario-name awsiam
        env:
          ANSIBLE_FORCE_COLOR: '1'
          AWS_ACCESS_KEY_ID_1: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY_1: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MOLECULE_VERBOSITY: 0
          PROFILE_TASKS_SORT_ORDER: 'none'
          PROFILE_TASKS_TASK_OUTPUT_LIMIT: '200'
          PY_COLORS: '1'
          TZ: 'Asia/Tokyo'

      - name: Set AWS access keys to environment variables
        run: |
          AWS_ACCESS_KEY_ID=$(cat /home/runner/.aws/credentials | grep aws_access_key_id | awk '{print $3}')
          AWS_SECRET_ACCESS_KEY=$(cat /home/runner/.aws/credentials | grep aws_secret_access_key | awk '{print $3}')
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $GITHUB_ENV

      - name: Set latest AMI image id to environment variables
        run: |
          sleep 20

          AMI_ID=$(aws ec2 describe-images \
          --owners "${{ secrets.AMI_OWNER_ID }}" \
          --filters "Name=name,Values=${{ matrix.platform }}_restore_${{ matrix.distro }}*" \
          --query 'Images[*][CreationDate, ImageId, Name]' \
          --output text | sort -r | awk 'NR==1 {print $2}')
          echo "AMI_ID=${AMI_ID}" >> $GITHUB_ENV
        env:
          # AWS_ACCESS_KEY_ID: sotred in system environment variables
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          # AWS_SECRET_ACCESS_KEY: sotred in system environment variables

      - name: Set environment variable with timestamp for making sure Molecule would create unique AWS resources
        run: |
          TIMESTAMP=$(date --date "9 hours" "+%Y%m%d_%H:%M:%S")
          VALUE=molecule_redmine_create-backup_${{ matrix.platform}}_${{ matrix.distro }}_${TIMESTAMP}
          echo "PLATFORM_NAME=${VALUE}" >> $GITHUB_ENV
          echo "KEYPAIR_NAME=${VALUE}" >> $GITHUB_ENV
          echo "SECURITY_GROUP_NAME=${VALUE}" >> $GITHUB_ENV
          echo "TAG_NAME=${VALUE}" >> $GITHUB_ENV

      - name: Set AWS resource creator name to system environment variables
        run: |
          author_email=$(git show -s --format='%ae' ${{ github.sha }})
          echo "CREATED_BY=$author_email" >> $GITHUB_ENV

      - name: Test with molecule
        run: |
          molecule test
        env:
          # AMI_ID: sotred in system environment variables
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_PYTHON_INTERPRETER: ${{ matrix.python_interpreter }}
          # AWS_ACCESS_KEY_ID: sotred in system environment variables
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_S3_BUCKET_NAME: "${{ secrets.AWS_S3_BUCKET_NAME }}-molecule"
          AWS_S3_OBJECT_NAME: "${{ matrix.platform }}/${{ matrix.distro }}/${{ secrets.AWS_S3_OBJECT_NAME }}"
          # AWS_SECRET_ACCESS_KEY: sotred in system environment variables
          # CREATED_BY: sotred in system environment variables
          # KEYPAIR_NAME: sotred in system environment variables
          LOCAL_FILE_NAME: ${{ secrets.AWS_S3_OBJECT_NAME }}
          MOLECULE_EC2_TAGS: "${{ matrix.platform }}_create-backup_${{ matrix.distro }}"
          # PLATFORM_NAME: sotred in system environment variables
          PROFILE_TASKS_SORT_ORDER: 'none'
          PROFILE_TASKS_TASK_OUTPUT_LIMIT: '200'
          TZ: 'Asia/Tokyo'
          PY_COLORS: '1'
          # SECURITY_GROUP_NAME: sotred in system environment variables
          # TAG_NAME: sotred in system environment variables
          # TIMESTAMP: sotred in system environment variables
          VPC_SUBNET_ID: ${{ secrets.VPC_SUBNET_ID }}

      - name: Delete AWS Access Key
        run: |
          molecule cleanup --scenario-name awsiam
        env:
          ANSIBLE_FORCE_COLOR: '1'
          AWS_ACCESS_KEY_ID_1: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY_1: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # AWSIAM_USER: sotred in system environment variables
          # AWSIAM_POLICY_NAME: sotred in system environment variables
          MOLECULE_VERBOSITY: 0
          PROFILE_TASKS_SORT_ORDER: 'none'
          PROFILE_TASKS_TASK_OUTPUT_LIMIT: '200'
          PY_COLORS: '1'
          TZ: 'Asia/Tokyo'

      - name: Show Ansible version
        run: |
          pip list | grep ansible \
          | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
          | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
          | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
          ansible --version

      - name: Show Molecule version
        run: |
          molecule --version
        env:
          PY_COLORS: '1'

  trailing-whitespace:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: harupy/find-trailing-whitespace@56310d70ae8fd21afec8d4307d2d9ab6c15e7c5d

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Execute yamllint
        run: yamllint *

      - name: Show yamllint version
        run: |
          yamllint --version \
          | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
          | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
          | GREP_COLORS='mt=01;33' egrep --color=always 'yamllint.* '
